services:
  db:
    image: postgres:17
    container_name: blog_db
    restart: unless-stopped
    volumes:
      - blog_db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 3

  django:
    build: .
    container_name: blog
    command: make serve
    restart: unless-stopped
    volumes:
      - .media/:/app/src/django_project/media/
      - ./static:/app/static_files
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: blog_redis
    restart: unless-stopped
    volumes:
      - blog_redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:latest
    container_name: blog_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/caddyfile
      - ./static:/static
      - ./media:/media
      - caddy_data:/data
      - caddy_config:/config


volumes:
  blog_db_data:
  blog_redis_data:
  caddy_data:
  caddy_config:
