# Generated by Django 6.0 on 2026-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_avatar_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="original_avatar_name",
            field=models.CharField(
                default="Image", verbose_name="Изначальное имя файла"
            ),
        ),
    ]
