# Generated by Django 6.0 on 2026-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_original_avatar_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="original_avatar_name",
            field=models.CharField(default=None, verbose_name="Изначальное имя файла"),
        ),
    ]
