# Generated by Django 6.0 on 2026-03-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_original_avatar_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="original_avatar_name",
            field=models.CharField(default="", verbose_name="Изначальное имя файла"),
        ),
    ]
