# Generated by Django 6.0 on 2025-12-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_rename_slag_category_slug_rename_slag_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog_app.category",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
