# Generated by Django 6.0 on 2025-12-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_alter_post_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
