# Generated by Django 6.0 on 2026-02-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog_app.category",
                verbose_name="Категории",
            ),
        ),
    ]
