# Generated by Django 6.0 on 2025-12-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_alter_post_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="key_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog_app.category",
            ),
        ),
    ]
