# Generated by Django 6.0 on 2026-03-07 08:35
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_alter_post_topic"),
    ]

    operations = [
        TrigramExtension()
    ]
