# Generated by Django 6.0 on 2026-03-09 07:24

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0008_post_post_title_content_gin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="post_title_content_gin",
        ),
        migrations.AddField(
            model_name="post",
            name="topic_title",
            field=models.CharField(
                default="", max_length=100, verbose_name="Название категории"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title", "content", "topic_title"],
                name="post_title_content_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
