# Generated by Django 6.0 on 2026-02-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(
                default="Прочее", max_length=100, verbose_name="Тема"
            ),
        ),
    ]
