# Generated by Django 6.0 on 2026-02-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0002_feedback_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.CharField(
                choices=[("Жалоба", "Жалоба"), ("Благодарность", "Благодарность")],
                default="Жалоба",
                max_length=100,
                verbose_name="Тема",
            ),
        ),
    ]
