# Generated by Django 6.0 on 2026-02-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0003_alter_feedback_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.CharField(
                default="Прочее", max_length=100, verbose_name="Тема"
            ),
        ),
    ]
